using System;
using System.Collections.Generic;
using YamiiDarkFantasy.Models;

namespace YamiiDarkFantasy.Models
{
    public static class SkillRegistry
    {
        public static readonly Dictionary<string, Skill> Skills = new()
        {
            { "attack", new Skill { Name = "こうげき", Description = "ぶきで てきを こうげきする", ScalingValue = "STR", Cooldown = 0, Bonus3Effect = "いりょくアップ", Bonus8Effect = "いりょくアップ" } },
            { "range_shot", new Skill { Name = "レンジショット", Description = "とおくの てきを こうげきする", ScalingValue = "DEX", Cooldown = 0, Bonus3Effect = "ついかこうげき", Bonus8Effect = "ついかこうげき" } },
            { "holy_bolt", new Skill { Name = "ホーリーボルト", Description = "せいなるひかりの ほとばしりで こうげきする", ScalingValue = "Faith", Cooldown = 0, Bonus3Effect = "いりょくアップ", Bonus8Effect = "ぼうぎょむし" } },
            { "punisher", new Skill { Name = "パニッシャー", Description = "ぶきで なぐりつけ かみの おしえを とく", ScalingValue = "Faith", Cooldown = 0, Bonus3Effect = "いりょくアップ", Bonus8Effect = "ぼうぎょむし" } },
            { "kunai", new Skill { Name = "くない", Description = "かくしもった くないを てきにとうてき", ScalingValue = "DEX", Cooldown = 0, Bonus3Effect = "ひっちゅう", Bonus8Effect = "いりょくアップ" } },
            { "pierce", new Skill { Name = "つきさす", Description = "ねらいをさだめて てきを つきさす", ScalingValue = "STR", Cooldown = 0, Bonus3Effect = "いりょくアップ", Bonus8Effect = "いりょくアップ" } },
            { "venom", new Skill { Name = "ベノム", Description = "てきを どくにおかして せいめいりょくを うばう", ScalingValue = "INT", Cooldown = 0, Bonus3Effect = "ターンえんちょう", Bonus8Effect = "ターンえんちょう" } },
            { "slash", new Skill { Name = "きりつける", Description = "ちからづよく てきを きりつける", ScalingValue = "STR", Cooldown = 0, Bonus3Effect = "ついかこうげき", Bonus8Effect = "ひっちゅう" } },
            { "dark_sphere", new Skill { Name = "ダークスフィア", Description = "あんこくのちからで てきを こうげきする", ScalingValue = "Faith", Cooldown = 0, Bonus3Effect = "いりょくアップ", Bonus8Effect = "いりょくアップ" } },
            { "wind_slash", new Skill { Name = "ウィンドスラッシュ", Description = "なんでも きりさく とっぷうを よびおこす", ScalingValue = "INT", Cooldown = 0, Bonus3Effect = "ついかこうげき", Bonus8Effect = "ついかこうげき" } },
            { "piercing_spear", new Skill { Name = "つらぬきのやり", Description = "ぼうぎょむし こうげき", ScalingValue = "STR", Cooldown = 0, Bonus3Effect = "いりょくアップ", Bonus8Effect = "いりょくアップ" } },
            { "wild_swing", new Skill { Name = "ぶんまわし", Description = "すごい いりょくだが むほうびになる", ScalingValue = "STR", Cooldown = 0, Bonus3Effect = "かくとく:きょうか/5ターン", Bonus8Effect = "かくとく:きょうか/5ターン" } },
            { "struggle", new Skill { Name = "わるあがき", Description = "めちゃくちゃに てきを こうげき", ScalingValue = "Level", Cooldown = 0, Bonus3Effect = "ついかこうげき", Bonus8Effect = "ついかこうげき" } },
            { "magic_missile", new Skill { Name = "マジックミサイル", Description = "まりょくの だんがんを れんぞくで しゃしゅ出する", ScalingValue = "INT", Cooldown = 0, BarrierCost = 1, Bonus3Effect = "ついかこうげき", Bonus8Effect = "ついかこうげき" } },
            { "energy_strike", new Skill { Name = "エナジーストライク", Description = "クリティカルしやすい まりょくの だんがんで こうげきする", ScalingValue = "INT", Cooldown = 0, Bonus3Effect = "いりょくアップ", Bonus8Effect = "いりょくアップ" } },
            { "moon_slash", new Skill { Name = "ムーンスラッシュ", Description = "こをえがく うつくしい れんげき", ScalingValue = "STR_Faith", Cooldown = 0, Bonus3Effect = "ついかこうげき", Bonus8Effect = "ついかこうげき" } },
            { "boomerang", new Skill { Name = "ブーメラン", Description = "ブーメランを なげて てきを こうげき", ScalingValue = "Level", Cooldown = 0, Bonus3Effect = "いりょくアップ", Bonus8Effect = "いりょくアップ" } },
            { "thunder_spark", new Skill { Name = "サンダースパーク", Description = "ほとばしる いなずまで こうげき。", ScalingValue = "INT_Faith", Cooldown = 0, Bonus3Effect = "いりょくアップ", Bonus8Effect = "ターンえんちょう" } },
            { "toxic_fluid", new Skill { Name = "もうどくえき", Description = "さいだいHPに おうじて ダメージを あたえる", ScalingValue = "EnemyMaxHP", Cooldown = 0, Bonus3Effect = "いりょくアップ", Bonus8Effect = "いりょくアップ" } },
            { "strike_rune", new Skill { Name = "ストライクルーン", Description = "こうげきしつつ こうげきりょくアップ", ScalingValue = "INT", Cooldown = 0, BarrierCost = 1, Bonus3Effect = "かくとく:きょうか/5ターン", Bonus8Effect = "きょうか/5ターン" } },
            { "reckless", new Skill { Name = "がむしゃら", Description = "3れんぞく こうげき", ScalingValue = "STR", Cooldown = 0, Bonus3Effect = "ついかこうげき", Bonus8Effect = "ついかこうげき" } },
            { "head_shot", new Skill { Name = "ヘッドシュート", Description = "てきに ダメージを あたえ、じぶんも てきも スタンする", ScalingValue = "Level", Cooldown = 0, Bonus3Effect = "スタン", Bonus8Effect = "スタン" } },
            { "penetration", new Skill { Name = "しんとう", Description = "ほんの すこしの ついげきを える。", ScalingValue = "INT", Cooldown = 0, Bonus3Effect = "ターンえんちょう", Bonus8Effect = "ターンえんちょう" } },
            { "air_cutter", new Skill { Name = "エアカッター", Description = "かぜの やいばで すばやく こうげき", ScalingValue = "INT", Cooldown = 0, Bonus3Effect = "ついかこうげき", Bonus8Effect = "ついかこうげき" } },
            { "wrath_fire", new Skill { Name = "いかりの ほのお", Description = "まりょくいぞん こうげき", ScalingValue = "INT", Cooldown = 0, BarrierCost = 1, Bonus3Effect = "いりょくアップ", Bonus8Effect = "いりょくアップ" } },
            { "nine_syllables", new Skill { Name = "くじ", Description = "とうほうに つたわる じゅもんを となえ こうげき", ScalingValue = "INT", Cooldown = 0, Bonus3Effect = "ついかこうげき", Bonus8Effect = "ついかこうげき" } },
            { "critical_knuckle", new Skill { Name = "クリティカルナックル", Description = "かならず クリティカルする いちげき", ScalingValue = "STR", Cooldown = 0, Bonus3Effect = "いりょくアップ", Bonus8Effect = "ひっちゅう" } },
            { "guide_fire", new Skill { Name = "ガイドファイア", Description = "てきを みつけたら じどうで こうげきする かきゅう", ScalingValue = "INT", Cooldown = 0, BarrierCost = 1, IsPreemptive = true, Bonus3Effect = "いりょくアップ", Bonus8Effect = "いりょくアップ" } },
            { "stance_aggressive", new Skill { Name = "スタンス:アグレッシブ", Description = "こうげきしつつ「かくしきば」をえるが うけるダメージが ふえる", ScalingValue = "Level", Cooldown = 0, Bonus3Effect = "ついかこうげき", Bonus8Effect = "ついかこうげき" } },
            { "stance_static", new Skill { Name = "スタンス:スタティック", Description = "こうげきしつつ「たいせい」をえるが めいちゅうりつが さがる", ScalingValue = "Level", Cooldown = 0, Bonus3Effect = "ついかこうげき", Bonus8Effect = "ついかこうげき" } },
            { "stance_passive", new Skill { Name = "スタンス:パッシブ", Description = "こうげきしつつ バリアを えるが クールダウンが のびる", ScalingValue = "Level", Cooldown = 0, Bonus3Effect = "ついかこうげき", Bonus8Effect = "ついかこうげき" } },
            { "ancient_spark", new Skill { Name = "エンシェントスパーク", Description = "じしんの シールドに おうじて いりょくが ます ふるい まじゅつ", ScalingValue = "Shield", Cooldown = 0, Bonus3Effect = "いりょくアップ", Bonus8Effect = "いりょくアップ" } },
            { "fireball", new Skill { Name = "ファイアーボール", Description = "ほのおのたまを なげつけて こうげきする", ScalingValue = "INT", Cooldown = 1, Bonus3Effect = "いりょくアップ", Bonus8Effect = "いりょくアップ" } },
            { "poison_trap", new Skill { Name = "ポイズントラップ", Description = "どくのわなで てきをこうげき", ScalingValue = "DEX", Cooldown = 1, Bonus3Effect = "ターンえんちょう", Bonus8Effect = "クールダウン-1" } },
            { "tackle", new Skill { Name = "タックル", Description = "ぜんしんで たいあたりする", ScalingValue = "STR", Cooldown = 1, Bonus3Effect = "スタン", Bonus8Effect = "クールダウン-1" } },
            { "aiming", new Skill { Name = "エイミング", Description = "ねらいをさだめて こうげき", ScalingValue = "DEX", Cooldown = 1, Bonus3Effect = "いりょくアップ", Bonus8Effect = "クールダウン-1" } },
            { "thunderbolt", new Skill { Name = "サンダーボルト", Description = "いかずちをおとし てきをこうげき", ScalingValue = "INT", Cooldown = 1, Bonus3Effect = "スタン", Bonus8Effect = "クールダウン-1" } },
            { "holy_bit", new Skill { Name = "ホーリービット", Description = "てきをついびし はれつする はっこうたいを はなつ", ScalingValue = "Faith", Cooldown = 1, Bonus3Effect = "ついか:もうもく/5ターン", Bonus8Effect = "クールダウン-1" } },
            { "march", new Skill { Name = "しんぐん", Description = "ぜんしんして えもので こうげき", ScalingValue = "STR", Cooldown = 1, IsPreemptive = true, Bonus3Effect = "ついかこうげき", Bonus8Effect = "ついかこうげき" } },
            { "bash", new Skill { Name = "バッシュ", Description = "ぶきやたてで てきを なぐりつける", ScalingValue = "STR", Cooldown = 1, Bonus3Effect = "いりょくアップ", Bonus8Effect = "ぼうぎょむし" } },
            { "fire_escape", new Skill { Name = "かとん", Description = "もえさかる ほのおで てきを つつみこむ", ScalingValue = "INT", Cooldown = 1, Bonus3Effect = "ターンえんちょう", Bonus8Effect = "ターンえんちょう" } },
            { "袈裟斬り", new Skill { Name = "けさぎり", Description = "おおぶりの ひとたちで てきを きりむすぶ", ScalingValue = "STR", Cooldown = 1, Bonus3Effect = "ひっちゅう", Bonus8Effect = "クールダウン-1" } },
            { "flame_torch", new Skill { Name = "フレイムトーチ", Description = "ほのおのついた たいまつを なげつける", ScalingValue = "DEX_INT", Cooldown = 1, Bonus3Effect = "いりょくアップ", Bonus8Effect = "クールダウン-1" } },
            { "holy_smite", new Skill { Name = "ホーリースマイト", Description = "あくをはらう せいなる こうげき", ScalingValue = "STR_Faith", Cooldown = 1, Bonus3Effect = "ついかこうげき", Bonus8Effect = "ついかこうげき" } },
            { "cut_through", new Skill { Name = "きりぬけ", Description = "すばやく こうげきしつつ かいひも たかめる", ScalingValue = "DEX", Cooldown = 1, Bonus3Effect = "かくとく:かいひ/1ターン", Bonus8Effect = "クールダウン-1" } },
            { "double_attack", new Skill { Name = "ダブルアタック", Description = "ぶきで てきを こうげきする", ScalingValue = "STR", Cooldown = 2, Bonus3Effect = "ついかこうげき", Bonus8Effect = "ついかこうげき" } },
            { "bleed", new Skill { Name = "ブリード", Description = "てきを きりつけ しゅっけつさせる", ScalingValue = "DEX", Cooldown = 1, Bonus3Effect = "ついか:しゅっけつ/15ターン", Bonus8Effect = "クールダウン-1" } },
            { "torment_hit", new Skill { Name = "トーメントヒット", Description = "さいなむ いちげきで じょうたいいじょうを うけやすくさせる。", ScalingValue = "Faith", Cooldown = 1, Bonus3Effect = "ターンえんちょう", Bonus8Effect = "クールダウン-1" } },
            { "heavens_sword", new Skill { Name = "ヘブンスソード", Description = "てんかいから もちだした つるぎで きりつける。", ScalingValue = "Faith_MaxHP", Cooldown = 1, Bonus3Effect = "かくとく:しぜんちゆ/10ターン", Bonus8Effect = "クールダウン-1" } },
            { "breaker", new Skill { Name = "ブレイカー", Description = "てきを なぐりつけて ぼうぎょりょくも さげる。", ScalingValue = "STR", Cooldown = 1, Bonus3Effect = "クールダウン-1", Bonus8Effect = "ターンえんちょう" } },
            { "quick_shot", new Skill { Name = "クイックショット", Description = "めにもとまらぬ すばやい いちげき。", ScalingValue = "DEX", Cooldown = 1, IsPreemptive = true, Bonus3Effect = "いりょくアップ", Bonus8Effect = "いりょくアップ" } },
            { "retribution", new Skill { Name = "ほうふく", Description = "じしんの はんしゃに おうじて てきに ダメージ", ScalingValue = "Reflect", Cooldown = 1, Bonus3Effect = "いりょくアップ", Bonus8Effect = "いりょくアップ" } },
            { "dark_bolt", new Skill { Name = "ダークボルト", Description = "やみの ちからで てきを こうげきし HPを うばう", ScalingValue = "Faith", Cooldown = 1, Bonus3Effect = "いりょくアップ", Bonus8Effect = "いりょくアップ" } },
            { "leg_sweep", new Skill { Name = "あしばらい", Description = "あしを はらい ダメージをあたえ スタンさせる", ScalingValue = "DEX", Cooldown = 1, Bonus3Effect = "スタン", Bonus8Effect = "スタン" } },
            { "enhance_sword", new Skill { Name = "エンハンスソード", Description = "こうげきしつつ ぶきを きょうか", ScalingValue = "STR", Cooldown = 1, Bonus3Effect = "かくとく:きょうか/2ターン", Bonus8Effect = "クールダウン-1" } },
            { "spell_mine", new Skill { Name = "スペルマイン", Description = "じかんけいかで はつどうする まほうの じらい", ScalingValue = "INT", Cooldown = 1, Bonus3Effect = "ターンたんしゅく", Bonus8Effect = "ターンたんしゅく" } },
            { "boost_strike", new Skill { Name = "ブーストストライク", Description = "ぼうぎょのための バリアを てきにたたきつける もろはのつるぎ", ScalingValue = "Level", Cooldown = 1, BarrierCost = 1, Bonus3Effect = "いりょくアップ", Bonus8Effect = "いりょくアップ" } },
            { "holy_spirit", new Skill { Name = "ホーリースピリット", Description = "てきを みつけだし こうげきしてくれる せんぞの れい", ScalingValue = "Faith", Cooldown = 1, BarrierCost = 1, IsPreemptive = true, Bonus3Effect = "いりょくアップ", Bonus8Effect = "いりょくアップ" } },
            { "vital_point", new Skill { Name = "きゅうしょねらい", Description = "こうげき、クリティカルじに ダメージが さらにアップ", ScalingValue = "STR", Cooldown = 1, Bonus3Effect = "いりょくアップ", Bonus8Effect = "いりょくアップ" } },
            { "death_sickle", new Skill { Name = "デスシックル", Description = "いのちを かりとる きんじられた じゃほう", ScalingValue = "EnemyHP", Cooldown = 1, Bonus3Effect = "いりょくアップ", Bonus8Effect = "いりょくアップ" } },
            { "martial_arts", new Skill { Name = "マーシャルアーツ", Description = "たさいな こうげきを どうじに くりだす", ScalingValue = "AllStat", Cooldown = 2, Bonus3Effect = "いりょくアップ", Bonus8Effect = "いりょくアップ" } },
            { "purify", new Skill { Name = "ピュリファイ", Description = "てんじょうから ひかりがふりそそぎ てきをじょうかする", ScalingValue = "Faith", Cooldown = 1, IsTurnFree = true, Bonus3Effect = "ついか:じゃくたい/5ターン", Bonus8Effect = "ついか:もうもく/5ターン" } },
            { "jab", new Skill { Name = "ジャブ", Description = "すばやいが かるいいちげき", ScalingValue = "STR", Cooldown = 1, IsTurnFree = true, Bonus3Effect = "ひっちゅう", Bonus8Effect = "いりょくアップ" } },
            { "feint", new Skill { Name = "フェイント", Description = "けんせいこうげき", ScalingValue = "DEX", Cooldown = 1, IsTurnFree = true, Bonus3Effect = "ついかこうげき", Bonus8Effect = "ついかこうげき" } },
            { "energy_bullet", new Skill { Name = "エナジーバレット", Description = "まりょくの だんがんを うちだす", ScalingValue = "INT", Cooldown = 1, IsTurnFree = true, Bonus3Effect = "ついかこうげき", Bonus8Effect = "ついかこうげき" } },
            { "spirit_bolt", new Skill { Name = "スピリットボルト", Description = "たましいの ほとばしりで こうげき", ScalingValue = "Faith", Cooldown = 1, IsTurnFree = true, Bonus3Effect = "いりょくアップ", Bonus8Effect = "いりょくアップ" } },
            { "sudden_gust", new Skill { Name = "サドンガスト", Description = "とつぜんの とっぷうで てきを こうげき", ScalingValue = "INT", Cooldown = 1, IsTurnFree = true, BarrierCost = 1, Bonus3Effect = "いりょくアップ", Bonus8Effect = "いりょくアップ" } },
            { "ice_needle", new Skill { Name = "アイスニードル", Description = "つららを つくりだし てきにはなって こうげきする", ScalingValue = "INT", Cooldown = 2, Bonus3Effect = "いりょくアップ", Bonus8Effect = "クールダウン-1" } },
            { "acid_rain", new Skill { Name = "アシッドレイン", Description = "てきを どくにおかして せいめいりょくを うばう", ScalingValue = "INT", Cooldown = 2, Bonus3Effect = "ターンえんちょう", Bonus8Effect = "クールダウン-1" } },
            { "smash", new Skill { Name = "スマッシュ", Description = "きょうれつな いちげきを くりだす", ScalingValue = "STR", Cooldown = 2, Bonus3Effect = "いりょくアップ", Bonus8Effect = "いりょくアップ" } },
            { "thrust", new Skill { Name = "スラスト", Description = "すばやいいちげきで てきをつく", ScalingValue = "DEX", Cooldown = 2, Bonus3Effect = "クールダウン-1", Bonus8Effect = "クールダウン-1" } },
            { "judgment", new Skill { Name = "ジャッジメント", Description = "かみのさばきをくだし じんだいな ひがいをもたらす", ScalingValue = "Faith", Cooldown = 2, Bonus3Effect = "ついか:もうもく/5ターン", Bonus8Effect = "ついか:じゃくたい/5ターン" } },
            { "holy_ray", new Skill { Name = "ホーリーレイ", Description = "ぼうぎょむし こうげき", ScalingValue = "Faith", Cooldown = 2, Bonus3Effect = "クールダウン-1", Bonus8Effect = "クールダウン-1" } },
            { "charge", new Skill { Name = "チャージ", Description = "てきに とつげきして たいあたり", ScalingValue = "STR", Cooldown = 2, IsPreemptive = true, Bonus3Effect = "いりょくアップ", Bonus8Effect = "ぼうぎょむし" } },
            { "shadow_shot", new Skill { Name = "シャドウショット", Description = "てきのしかく かげからの いちげき", ScalingValue = "DEX", Cooldown = 2, IsPreemptive = true, Bonus3Effect = "いりょくアップ", Bonus8Effect = "ついか:ダメージぞうか/5ターン" } },
            { "wind_dance", new Skill { Name = "かぜの まい", Description = "みやびな まいで てきを こうげき", ScalingValue = "DEX_INT", Cooldown = 2, Bonus3Effect = "ついかこうげき", Bonus8Effect = "ついかこうげき" } },
            { "pop", new Skill { Name = "はじける", Description = "はじけて ひまつを ぶつける。", ScalingValue = "AllStat", Cooldown = 2, IsPreemptive = true, Bonus3Effect = "ターンえんちょう", Bonus8Effect = "ターンえんちょう" } },
            { "full_swing", new Skill { Name = "フルスウィング", Description = "ぜんりょくで ぶきをふりかぶり てきにたたきつける", ScalingValue = "STR", Cooldown = 2, Bonus3Effect = "ついか:ダメージぞうか/5ターン", Bonus8Effect = "ついか:ダメージぞうか/5ターン" } },
            { "tornado", new Skill { Name = "トルネード", Description = "たつまきを よびだし てきをまきあげる", ScalingValue = "INT", Cooldown = 2, Bonus3Effect = "ついかこうげき", Bonus8Effect = "ついかこうげき" } },
            { "thunder_strike", new Skill { Name = "サンダーストライク", Description = "でんげきを まとった いちげきを くりだす", ScalingValue = "STR_INT", Cooldown = 2, Bonus3Effect = "ついかこうげき", Bonus8Effect = "ついかこうげき" } },
            { "valkyrie_spear", new Skill { Name = "ヴァルキリースピア", Description = "きょうれつな いちげきを くりだす", ScalingValue = "STR_Faith", Cooldown = 2, Bonus3Effect = "ついかこうげき", Bonus8Effect = "ついかこうげき" } },
            { "heavens_ray", new Skill { Name = "ヘブンスレイ", Description = "てんじょうより こうせんを よびよせ じかんさ こうげき", ScalingValue = "Faith", Cooldown = 2, Bonus3Effect = "ターンたんしゅく", Bonus8Effect = "ターンたんしゅく" } },
            { "shotgun", new Skill { Name = "ショットガン", Description = "さんだんで てきを こうげき", ScalingValue = "Level", Cooldown = 2, Bonus3Effect = "ついかこうげき", Bonus8Effect = "ついかこうげき" } },
            { "bear_trap", new Skill { Name = "ベアトラップ", Description = "てきの こうげきを はんしゃする するどい やいば。", ScalingValue = "DEX", Cooldown = 2, Bonus3Effect = "ターンえんちょう", Bonus8Effect = "ターンえんちょう" } },
            { "gravity_press", new Skill { Name = "グラビティプレス", Description = "じゅうりょくで てきを おしつぶす", ScalingValue = "EnemyHP", Cooldown = 2, Bonus3Effect = "いりょくアップ", Bonus8Effect = "いりょくアップ" } },
            { "aura_cannon", new Skill { Name = "オーラキャノン", Description = "せいめいりょくを ちょくせつ こうげきに かえる", ScalingValue = "CurrentHP", Cooldown = 2, Bonus3Effect = "いりょくアップ", Bonus8Effect = "かくとく:しぜんちゆ/3ターン" } },
            { "dagger_throw", new Skill { Name = "ダガースロー", Description = "ふところに かくした ダガーを なげつける", ScalingValue = "DEX", Cooldown = 2, IsTurnFree = true, Bonus3Effect = "クールダウン-1", Bonus8Effect = "いりょくアップ" } },
            { "stone_throw", new Skill { Name = "いしつぶて", Description = "いしつぶてを なげつけて こうげき", ScalingValue = "DEX_INT", Cooldown = 2, IsTurnFree = true, Bonus3Effect = "ついかこうげき", Bonus8Effect = "ついかこうげき" } },

            // 防御・回復・補助系
            { "guard", new Skill { Name = "ガード", Description = "ぼうぎょにてっし このターンにうける ダメージをけいげんする", SkillType = "Buff", Cooldown = 1, AppliesToSelf = true, Bonus3Effect = "かくとく:けいげん/1ターン", Bonus8Effect = "かくとく:けいげん/1ターン" } },
            { "back_step", new Skill { Name = "バックステップ", Description = "かいひにてっし このターンにうける こうげきを かいひする", SkillType = "Buff", Cooldown = 1, AppliesToSelf = true, Bonus3Effect = "かくとく:かいひ/1ターン", Bonus8Effect = "かくとく:かいひ/5ターン" } },
            { "parry", new Skill { Name = "うけながし", Description = "ぼうぎょの かまえで このターンの てきのこうげきを うけながす", SkillType = "Buff", Cooldown = 1, Bonus3Effect = "いりょくアップ", Bonus8Effect = "いりょくアップ" } },
            { "hide", new Skill { Name = "かくれる", Description = "ぜんスキルの クールダウンと ひきかえに おおはばに かいひアップ", SkillType = "Buff", Cooldown = 1, AppliesToSelf = true, Bonus3Effect = "ターンえんちょう", Bonus8Effect = "ターンえんちょう" } },
            { "barrier_boost", new Skill { Name = "バリアブースト", Description = "バリアをはる(+2)", SkillType = "Buff", Cooldown = 1, BarrierCost = 1, AppliesToSelf = true, Bonus3Effect = "かくとく:けいげん/5ターン", Bonus8Effect = "クールダウン-1" } },
            { "stance_defensive", new Skill { Name = "スタンス:ディフェンシブ", Description = "ぼうぎょてきな スタイルで たたかう", SkillType = "Buff", Cooldown = 1, IsTurnFree = true, AppliesToSelf = true, Bonus3Effect = "かくとく:けいげん/5ターン", Bonus8Effect = "かくとく:けいげん/5ターン" } },
            { "barrier", new Skill { Name = "バリア", Description = "バリアをはる(+1)", SkillType = "Buff", Cooldown = 2, AppliesToSelf = true, Bonus3Effect = "かくとく:けいげん/5ターン", Bonus8Effect = "クールダウン-1" } },
            { "phalanx", new Skill { Name = "ファランクス", Description = "すきのない ぼうぎょのかまえで このターンに うけるダメージを げきげん", SkillType = "Buff", Cooldown = 2, AppliesToSelf = true, Bonus3Effect = "かくとく:けいげん/5ターン", Bonus8Effect = "クールダウン-1" } },
            { "confinement", new Skill { Name = "ろうじょう", Description = "このターンに あたえるダメージと うけるダメージを おおきくへらす", SkillType = "Buff", Cooldown = 2, IsTurnFree = true, AppliesToSelf = true, Bonus3Effect = "かくとく:けいげん/5ターン", Bonus8Effect = "かくとく:けいげん/10ターン" } },
            { "force_field", new Skill { Name = "フォースフィールド", Description = "ダメージを かたがわりしてくれる シールドを うみだす", SkillType = "Buff", ScalingValue = "INT", Cooldown = 3, AppliesToSelf = true, Bonus3Effect = "いりょくアップ", Bonus8Effect = "いりょくアップ" } },
            { "sacred_barrier", new Skill { Name = "セイクリッドバリア", Description = "ダメージを かたがわりしてくれる シールドを うみだす", SkillType = "Buff", ScalingValue = "Faith", Cooldown = 3, AppliesToSelf = true, Bonus3Effect = "いりょくアップ", Bonus8Effect = "いりょくアップ" } },
            { "double_shield", new Skill { Name = "ダブルシールド", Description = "シールドを ばいに ふやす", SkillType = "Buff", ScalingValue = "Shield", Cooldown = 3, BarrierCost = 2, AppliesToSelf = true, Bonus3Effect = "クールダウン-1", Bonus8Effect = "クールダウン-1" } },
            { "protection", new Skill { Name = "プロテクション", Description = "うけるダメージを へらす ぼうごまほうを じぶんにかける", SkillType = "Buff", Cooldown = 3, IsTurnFree = true, AppliesToSelf = true, Bonus3Effect = "いりょくアップ", Bonus8Effect = "いりょくアップ" } },
            { "acrobatics", new Skill { Name = "アクロバット", Description = "いちじてきに かいひを たかめる", SkillType = "Buff", Cooldown = 3, IsTurnFree = true, AppliesToSelf = true, Bonus3Effect = "いりょくアップ", Bonus8Effect = "いりょくアップ" } },
            { "distance", new Skill { Name = "ディスタンス", Description = "てきから きょりをとり たがいの めいちゅうを さげる", SkillType = "Buff", Cooldown = 3, IsTurnFree = true, Bonus3Effect = "かくとく:かいひ/3ターン", Bonus8Effect = "かくとく:かいひ/3ターン" } },
            { "barrier_gain", new Skill { Name = "バリアゲイン", Description = "いちじてきに せんとうかいしじに えられる バリアを ふやす", SkillType = "Buff", Cooldown = 3, IsTurnFree = true, AppliesToSelf = true, Bonus3Effect = "ターンえんちょう", Bonus8Effect = "ターンえんちょう" } },
            { "deflect", new Skill { Name = "ディフレクト", Description = "ぶきで てきのこうげきを うけながし このターンにうける ダメージをけいげんする", SkillType = "Buff", Cooldown = 3, IsTurnFree = true, AppliesToSelf = true, Bonus3Effect = "いりょくアップ", Bonus8Effect = "かくとく:けいげん/10ターン" } },
            { "pharmacy", new Skill { Name = "やくがく", Description = "てきに あたえている けいぞくダメージにおうじて シールドをえる", SkillType = "Buff", ScalingValue = "EnemyDoT", Cooldown = 3, IsTurnFree = true, AppliesToSelf = true, Bonus3Effect = "クールダウン-1", Bonus8Effect = "クールダウン-1" } },
            { "shield_force", new Skill { Name = "シールドフォース", Description = "シールドをえる", SkillType = "Buff", ScalingValue = "MaxHP", Cooldown = 4, AppliesToSelf = true, Bonus3Effect = "クールダウン-1", Bonus8Effect = "クールダウン-1" } },
            { "back_flip", new Skill { Name = "バックフリップ", Description = "かいひにてっし このターンにうける こうげきを ほぼかくじつに かいひする", SkillType = "Buff", Cooldown = 4, AppliesToSelf = true, Bonus3Effect = "クールダウン-1", Bonus8Effect = "クールダウン-1" } },
            { "shield_gain", new Skill { Name = "シールドゲイン", Description = "いちじてきに せんとうかいしじに えられる シールドを ふやす", SkillType = "Buff", ScalingValue = "Level", Cooldown = 4, IsTurnFree = true, AppliesToSelf = true, Bonus3Effect = "ターンえんちょう", Bonus8Effect = "ターンえんちょう" } },
            { "mental_state", new Skill { Name = "しんとうめっきゃく", Description = "どんな くきょうにも まけない こころで ダメージけいげんと たいせいを える", SkillType = "Buff", Cooldown = 4, IsTurnFree = true, AppliesToSelf = true, Bonus3Effect = "かくとく:たいせい/5ターン", Bonus8Effect = "かくとく:けいげん/5ターン" } },
            { "spell_shield", new Skill { Name = "スペルシールド", Description = "バリアをはる(+3)", SkillType = "Buff", Cooldown = 5, AppliesToSelf = true, Bonus3Effect = "いりょくアップ", Bonus8Effect = "クールダウン-1" } },
            { "natural_selection", new Skill { Name = "てきしゃせいぞん", Description = "しばらくのあいだ かいひと クリティカルりつが アップ", SkillType = "Buff", Cooldown = 5, IsTurnFree = true, AppliesToSelf = true, Bonus3Effect = "クールダウン-1", Bonus8Effect = "クールダウン-1" } },
            { "light_band", new Skill { Name = "ひかりの おび", Description = "オーバーヒールと バーストヒールと せいなるかごを える", SkillType = "Buff", Cooldown = 5, IsTurnFree = true, AppliesToSelf = true, Bonus3Effect = "かくとく:かいふく/5ターン", Bonus8Effect = "かくとく:しぜんちゆ/10ターン" } },
            { "blood_shield", new Skill { Name = "ブラッドシールド", Description = "HPを しょうひして シールドを える", SkillType = "Buff", ScalingValue = "MaxHP", Cooldown = 5, IsTurnFree = true, AppliesToSelf = true, Bonus3Effect = "クールダウン-1", Bonus8Effect = "クールダウン-1" } },
            { "mirror_coat", new Skill { Name = "ミラーコート", Description = "いちじてきに「きょうめん」をえて てきの はんしゃを ふせぐ", SkillType = "Buff", Cooldown = 5, IsTurnFree = true, AppliesToSelf = true, Bonus3Effect = "ターンえんちょう", Bonus8Effect = "ターンえんちょう" } },
            { "wind_shield", new Skill { Name = "ウィンドシールド", Description = "かぜを まとって ぼうぎょする", SkillType = "Buff", Cooldown = 5, IsTurnFree = true, AppliesToSelf = true, Bonus3Effect = "クールダウン-1", Bonus8Effect = "クールダウン-1" } },
            { "resurrection", new Skill { Name = "リザレクション", Description = "このターンは しんでも すぐによみがえる", SkillType = "Buff", Cooldown = 6, IsTurnFree = true, Bonus3Effect = "かくとく:しぜんちゆ/5ターン", Bonus8Effect = "かくとく:しぜんちゆ/10ターン" } },
            { "rear_guard", new Skill { Name = "しんがり", Description = "いちじてきに せんとうかいしじに えられる バリアを ふやす", SkillType = "Buff", Cooldown = 6, IsTurnFree = true, Bonus3Effect = "ターンえんちょう", Bonus8Effect = "ターンえんちょう" } },
            { "shelter", new Skill { Name = "しゃへいぶつ", Description = "シールドを える", SkillType = "Buff", ScalingValue = "Level", Cooldown = 6, IsTurnFree = true, Bonus3Effect = "クールダウン-1", Bonus8Effect = "クールダウン-1" } },
            { "dissolve_in_shadow", new Skill { Name = "かげに とける", Description = "いちじてきに むてきになる", SkillType = "Buff", Cooldown = 7, Bonus3Effect = "ターンえんちょう", Bonus8Effect = "ターンえんちょう" } },
            { "steel_body", new Skill { Name = "こうてつの にくたい", Description = "シールドをえる", SkillType = "Buff", ScalingValue = "MaxHP", Cooldown = 8, Bonus3Effect = "クールダウン-1", Bonus8Effect = "クールダウン-1" } },
            { "blink", new Skill { Name = "ブリンク", Description = "バリアをはる(+5)", SkillType = "Buff", Cooldown = 8, Bonus3Effect = "いりょくアップ", Bonus8Effect = "クールダウン-1" } },
            { "ancient_shield", new Skill { Name = "エンシェントシールド", Description = "まりょくを シールドに へんかんする ふるい まじゅつ", SkillType = "Buff", ScalingValue = "INT", Cooldown = 10, IsTurnFree = true, Bonus3Effect = "クールダウン-1", Bonus8Effect = "クールダウン-1" } },

            // 回復系
            { "doping", new Skill { Name = "ドーピング", Description = "いちじてきに HPを かいふくするが じょじょに うしなう", SkillType = "Heal", ScalingValue = "MaxHP", Cooldown = 0, Bonus3Effect = "かくとく:かいふく/5ターン", Bonus8Effect = "かくとく:かいふく/5ターン" } },
            { "spirit_breath", new Skill { Name = "とうき", Description = "じぶんの マイナスこうかを すべてうちけす", SkillType = "Heal", Cooldown = 0, IsTurnFree = true, BarrierCost = 1, Bonus3Effect = "かくとく:たいせい/5ターン", Bonus8Effect = "かくとく:たいせい/5ターン" } },
            { "first_aid", new Skill { Name = "おうきゅうてあて", Description = "てばやく きずを ちりょうする", SkillType = "Heal", ScalingValue = "MaxHP", Cooldown = 1, Bonus3Effect = "じょうたいいじょうを 1つ ちりょう", Bonus8Effect = "クールダウン-1" } },
            { "cure_wounds", new Skill { Name = "キュアウーンズ", Description = "かんたんな きずのてあてをして HPを かいふくする", SkillType = "Heal", ScalingValue = "CurrentHP", Cooldown = 1, Bonus3Effect = "いりょくアップ", Bonus8Effect = "いりょくアップ" } },
            { "deep_sleep", new Skill { Name = "じゅくすい", Description = "ぜんスキルの クールダウンと ひきかえに HPぜんかいふく", SkillType = "Heal", ScalingValue = "MaxHP", Cooldown = 1, Bonus3Effect = "じょうたいいじょうを すべて ちりょう", Bonus8Effect = "かくとく:しぜんちゆ/10ターン" } },
            { "healing", new Skill { Name = "ヒーリング", Description = "HPを かいふくする", SkillType = "Heal", ScalingValue = "MaxHP", Cooldown = 2, Bonus3Effect = "かくとく:かいふく/5ターン", Bonus8Effect = "クールダウン-1" } },
            { "regeneration", new Skill { Name = "リジェネレーション", Description = "じょじょに HPをかいふくする", SkillType = "Heal", ScalingValue = "MaxHP", Cooldown = 2, Bonus3Effect = "ターンえんちょう", Bonus8Effect = "ターンえんちょう" } },
            { "life_wave", new Skill { Name = "せいめいはどう", Description = "HPを かいふくする", SkillType = "Heal", ScalingValue = "Shield", Cooldown = 2, Bonus3Effect = "シールドかくとく", Bonus8Effect = "シールドかくとく" } },
            { "healing_breath", new Skill { Name = "いやしの こきゅう", Description = "ほんのすこし HPを かいふくする こきゅうほう", SkillType = "Heal", ScalingValue = "MaxHP", Cooldown = 2, IsTurnFree = true, Bonus3Effect = "いりょくアップ", Bonus8Effect = "いりょくアップ" } },
            { "moon_heal", new Skill { Name = "ムーンヒール", Description = "HPを かいふくする", SkillType = "Heal", ScalingValue = "Faith", Cooldown = 2, IsTurnFree = true, Bonus3Effect = "じょうたいいじょうを 1つ ちりょう", Bonus8Effect = "クールダウン-1" } },
            { "chakra", new Skill { Name = "チャクラ", Description = "じょじょに HPをかいふくする", SkillType = "Heal", ScalingValue = "CurrentHP", Cooldown = 3, Bonus3Effect = "じょうたいいじょうを 1つ ちりょう", Bonus8Effect = "クールダウン-1" } },
            { "life_growth", new Skill { Name = "ライフグロース", Description = "かんたんな きずのてあてをして HPを かいふくする", SkillType = "Heal", ScalingValue = "CurrentHP", Cooldown = 3, Bonus3Effect = "クールダウン-1", Bonus8Effect = "クールダウン-1" } },
            { "blood_curse", new Skill { Name = "ちのけがれ", Description = "HPを かんぜんかいふく するが じょうたいいじょうに よわくなる", SkillType = "Heal", ScalingValue = "MaxHP", Cooldown = 3, Bonus3Effect = "ついか:おせん/5ターン", Bonus8Effect = "クールダウン-1" } },
            { "detox", new Skill { Name = "デトックス", Description = "じぶんの マイナスこうかを 1つうちけす", SkillType = "Heal", Cooldown = 3, IsTurnFree = true, Bonus3Effect = "クールダウン-1", Bonus8Effect = "クールダウン-1" } },
            { "high_healing", new Skill { Name = "ハイヒーリング", Description = "HPを おおきく かいふくする", SkillType = "Heal", ScalingValue = "MaxHP", Cooldown = 4, Bonus3Effect = "いりょくアップ", Bonus8Effect = "いりょくアップ" } },
            { "angel_care", new Skill { Name = "エンジェルケア", Description = "HPを かいふくして どうじに シールドも える", SkillType = "Heal", ScalingValue = "MaxHP", Cooldown = 4, Bonus3Effect = "クールダウン-1", Bonus8Effect = "じょうたいいじょうを すべて ちりょう" } },
            { "fairy_powder", new Skill { Name = "フェアリーパウダー", Description = "じぶんの マイナスこうかを 1つうちけし さらに バリアをはる(+1)", SkillType = "Heal", Cooldown = 4, Bonus3Effect = "バリアかくとく", Bonus8Effect = "クールダウン-1" } },
            { "instant_heal", new Skill { Name = "インスタントヒール", Description = "しんこうの かごにより すぐさま HPを かいふくする", SkillType = "Heal", ScalingValue = "MaxHP", Cooldown = 4, IsTurnFree = true, Bonus3Effect = "クールダウン-1", Bonus8Effect = "クールダウン-1" } },
            { "full_healing", new Skill { Name = "フルヒーリング", Description = "HPを かんぜんかいふくする", SkillType = "Heal", ScalingValue = "MaxHP", Cooldown = 5, Bonus3Effect = "クールダウン-1", Bonus8Effect = "クールダウン-1" } },
            { "divine_heal", new Skill { Name = "ディバインヒール", Description = "せいなる ちからで みずからの きずを いやす", SkillType = "Heal", ScalingValue = "Faith", Cooldown = 5, IsTurnFree = true, Bonus3Effect = "クールダウン-1", Bonus8Effect = "じょうたいいじょうを すべて ちりょう" } },
            { "refresh", new Skill { Name = "リフレッシュ", Description = "じぶんの すべてのこうかを うちけす きぶんスッキリ", SkillType = "Heal", Cooldown = 5, IsTurnFree = true, Bonus3Effect = "クールダウン-1", Bonus8Effect = "クールダウン-1" } },
            { "unyielding", new Skill { Name = "ふとうふくつ", Description = "いちじてきに じょうたいいじょうを うけにくくする", SkillType = "Buff", Cooldown = 5, IsTurnFree = true, Bonus3Effect = "ターンえんちょう", Bonus8Effect = "ターンえんちょう" } },
            { "restore_body", new Skill { Name = "リストアボディ", Description = "じぶんの マイナスこうかを すべてうちけす", SkillType = "Heal", Cooldown = 5, IsTurnFree = true, Bonus3Effect = "クールダウン-1", Bonus8Effect = "クールダウン-1" } },
            { "spirit", new Skill { Name = "こんじょう", Description = "こんじょうで かいふくりょうが げきてきに アップ！", SkillType = "Buff", Cooldown = 5, IsTurnFree = true, Bonus3Effect = "クールダウン-1", Bonus8Effect = "クールダウン-1" } },
            { "sacred_boundary", new Skill { Name = "せいなる けっかい", Description = "HPをかいふくし、シールドと バリアを えて、 じょうたいいじょうを 1つ ちりょうする。", SkillType = "Heal", ScalingValue = "MaxHP", Cooldown = 10, Bonus3Effect = "クールダウン-1", Bonus8Effect = "クールダウン-1" } },

            // 強力なバフ・その他
            { "dragon_aura", new Skill { Name = "ドラゴンオーラ", Description = "いちじてきに せんとうのうりょくが げきてきに アップ", SkillType = "Buff", Cooldown = 0, IsTurnFree = true, BarrierCost = 5, Bonus3Effect = "かくとく:きょうか/25ターン", Bonus8Effect = "かくとく:けいげん/25ターン" } },
            { "counter", new Skill { Name = "カウンター", Description = "このターン てきの こうげきに はんげきする", SkillType = "Buff", ScalingValue = "STR", Cooldown = 1, Bonus3Effect = "いりょくアップ", Bonus8Effect = "クールダウン-1" } },
            { "offensive", new Skill { Name = "オフェンシブ", Description = "こうげきてきな スタイルで たたかう", SkillType = "Buff", Cooldown = 1, IsTurnFree = true, Bonus3Effect = "かくとく:きょうか/5ターン", Bonus8Effect = "かくとく:きょうか/5ターン" } },
            { "desperado", new Skill { Name = "デスペラード", Description = "いちじてきに あたえるダメージと うけるダメージを おおはばに ふやす", SkillType = "Buff", Cooldown = 1, IsTurnFree = true, Bonus3Effect = "かくとく:きょうか/10ターン", Bonus8Effect = "かくとく:きょうか/10ターン" } },
            { "bloody_edge", new Skill { Name = "ブラッディエッジ", Description = "いのちをぎせいにして このターンのあいだ こうげきりょくを おおきくあげる", SkillType = "Buff", ScalingValue = "MaxHP", Cooldown = 1, IsTurnFree = true, Bonus3Effect = "かくとく:きょうか/3ターン", Bonus8Effect = "かくとく:きょうか/3ターン" } },
            { "focus_energy", new Skill { Name = "ちからため", Description = "つぎのターンに いりょくアップ", SkillType = "Buff", Cooldown = 2, Bonus3Effect = "クールダウン-1", Bonus8Effect = "クールダウン-1" } },
            { "revenge", new Skill { Name = "リベンジ", Description = "てきの こうげきに はんのうして はんげきする", SkillType = "Buff", ScalingValue = "MaxHP", Cooldown = 2, Bonus3Effect = "クールダウン-1", Bonus8Effect = "クールダウン-1" } },
            { "hell_contract", new Skill { Name = "ヘルコントラクト", Description = "しばらくのあいだ シールドぶんだけ こうげきりょくが アップ", SkillType = "Buff", ScalingValue = "Shield", Cooldown = 2, BarrierCost = 1, Bonus3Effect = "いりょくアップ", Bonus8Effect = "いりょくアップ" } },
            { "sacrifice", new Skill { Name = "サクリファイス", Description = "ほじょこうかの じかんを ええんちょうする", SkillType = "Buff", Cooldown = 2, BarrierCost = 2, Bonus3Effect = "クールダウン-1", Bonus8Effect = "クールダウン-1" } },
            { "quick_draw", new Skill { Name = "クイックドロー", Description = "1つのスキルの クールダウンを 1へらす", SkillType = "Buff", Cooldown = 2, IsTurnFree = true, Bonus3Effect = "いずれかのスキル クールダウン-1", Bonus8Effect = "いずれかのスキル クールダウン-1" } },
            { "shadow_walk", new Skill { Name = "かげわたり", Description = "めにもとまらぬ はやわざで このターンに すべてのスキルを しようできる", SkillType = "Buff", Cooldown = 2, IsTurnFree = true, Bonus3Effect = "かくとく:きょうか/1ターン", Bonus8Effect = "クールダウン-1" } },
            { "eagle_eye", new Skill { Name = "イーグルアイ", Description = "いちじてきに めいちゅうを たかめる", SkillType = "Buff", Cooldown = 3, IsTurnFree = true, Bonus3Effect = "かくとく:めいちゅう/10ターン", Bonus8Effect = "かくとく:じどうついび/15ターン" } },
            { "heat_up", new Skill { Name = "ヒートアップ", Description = "いちじてきに クリティカルりつを たかめる", SkillType = "Buff", Cooldown = 3, IsTurnFree = true, Bonus3Effect = "ターンえんちょう", Bonus8Effect = "ターンえんちょう" } },
            { "magic_sword", new Skill { Name = "まほうけん", Description = "ぶきに まほうをふよし きんりょくをアップ", SkillType = "Buff", ScalingValue = "INT", Cooldown = 3, IsTurnFree = true, Bonus3Effect = "ターンえんちょう", Bonus8Effect = "ターンえんちょう" } },
            { "faith_wing", new Skill { Name = "しんこうのつばさ", Description = "しんこうのかごをえて ぎりょうをアップ", SkillType = "Buff", ScalingValue = "Faith", Cooldown = 3, IsTurnFree = true, Bonus3Effect = "ターンえんちょう", Bonus8Effect = "ターンえんちょう" } },
            { "speed_chant", new Skill { Name = "こうそくえいしょう", Description = "えいしょうを かそくすることで まりょくをアップ", SkillType = "Buff", ScalingValue = "DEX", Cooldown = 3, IsTurnFree = true, Bonus3Effect = "ターンえんちょう", Bonus8Effect = "ターンえんちょう" } },
            { "crusade", new Skill { Name = "クルセイド", Description = "そのみを せいせんにささげ しんこうをアップ", SkillType = "Buff", ScalingValue = "STR", Cooldown = 3, IsTurnFree = true, Bonus3Effect = "ターンえんちょう", Bonus8Effect = "ターンえんちょう" } },
            { "hatred", new Skill { Name = "ヘイトレッド", Description = "しばらくのあいだ HPがへるほど あたえるダメージが ふえる", SkillType = "Buff", Cooldown = 3, IsTurnFree = true, Bonus3Effect = "かくとく:きょうか/5ターン", Bonus8Effect = "かくとく:きょうか/5ターン" } },
            { "haste", new Skill { Name = "ヘイスト", Description = "ときのながれを かそくし つぎのターンに つかう スキルの クールダウンを けいげんする", SkillType = "Buff", Cooldown = 4, Bonus3Effect = "ターンえんちょう", Bonus8Effect = "クールダウン-1" } },
            { "focus", new Skill { Name = "フォーカス", Description = "このターン めいちゅうが ひやくてきに たかまる", SkillType = "Buff", Cooldown = 4, IsTurnFree = true, Bonus3Effect = "かくとく:めいちゅう/5ターン", Bonus8Effect = "かくとく:じどうついび/5ターン" } },
            { "angel_light", new Skill { Name = "エンジェルライト", Description = "HPを かいふくし さらに いちじてきに HPかいふくりょうを ふやす", SkillType = "Heal", ScalingValue = "MaxHP", Cooldown = 4, IsTurnFree = true, Bonus3Effect = "じょうたいいじょうを 1つ ちりょう", Bonus8Effect = "クールダウン-1" } },
            { "insight", new Skill { Name = "かんぱ", Description = "このターン クリティカルりつが ひやくてきに たかまる", SkillType = "Buff", Cooldown = 4, IsTurnFree = true, Bonus3Effect = "クールダウン-1", Bonus8Effect = "クールダウン-1" } },
            { "overflow", new Skill { Name = "オーバーフロー", Description = "せいしんを ぼうそうさせ つぎのターン こうげきいりょくを ぞうだいさせる", SkillType = "Buff", Cooldown = 5, Bonus3Effect = "かくとく:きょうか/5ターン", Bonus8Effect = "かくとく:きょうか/25ターン" } },
            { "now_is_the_time", new Skill { Name = "いま だ！", Description = "つぎのターンに クリティカルダメージを げきてきに アップ", SkillType = "Buff", Cooldown = 5, Bonus3Effect = "いりょくアップ", Bonus8Effect = "いりょくアップ" } },
            { "smoke_screen", new Skill { Name = "えんまく", Description = "えんまくで てきを かくらんし せんとうを ゆうりに はこぶ", SkillType = "Debuff", Cooldown = 5, Bonus3Effect = "ターンえんちょう", Bonus8Effect = "ターンえんちょう" } },
            { "high_voltage", new Skill { Name = "ハイボルテージ", Description = "バリアを エネルギーに へんかんし ばくはつてきな こうげきりょくを える", SkillType = "Buff", Cooldown = 5, BarrierCost = 3, Bonus3Effect = "いりょくアップ", Bonus8Effect = "いりょくアップ" } },
            { "war_cry", new Skill { Name = "ウォークライ", Description = "しばらくのあいだ きんりょ力を たかめる", SkillType = "Buff", Cooldown = 5, IsTurnFree = true, Bonus3Effect = "いりょくアップ", Bonus8Effect = "いりょくアップ" } },
            { "quick_move", new Skill { Name = "クイックムーブ", Description = "しばらくのあいだ ぎりょうを たかめる", SkillType = "Buff", Cooldown = 5, IsTurnFree = true, Bonus3Effect = "いりょくアップ", Bonus8Effect = "いりょくアップ" } },
            { "concentration", new Skill { Name = "コンセントレーション", Description = "しばらくのあいだ まりょくを たかめる", SkillType = "Buff", Cooldown = 5, IsTurnFree = true, Bonus3Effect = "いりょくアップ", Bonus8Effect = "いりょくアップ" } },
            { "meditation", new Skill { Name = "メディテーション", Description = "しばらくのあいだ しんこうを たかめる", SkillType = "Buff", Cooldown = 5, IsTurnFree = true, Bonus3Effect = "いりょくアップ", Bonus8Effect = "いりょくアップ" } },
            { "dragon_fang", new Skill { Name = "りゅうのきば", Description = "てきの こうげきに はんのうして はんげきする", SkillType = "Buff", ScalingValue = "CurrentHP", Cooldown = 5, IsTurnFree = true, Bonus3Effect = "クールダウン-1", Bonus8Effect = "クールダウン-1" } },
            { "thrust_stance", new Skill { Name = "しとつの かまえ", Description = "いちじてきに こうげきりょくを たかめ かんつうを える", SkillType = "Buff", Cooldown = 5, IsTurnFree = true, Bonus3Effect = "クールダウン-1", Bonus8Effect = "クールダウン-1" } },
            { "sniper_stance", new Skill { Name = "そげきたいせい", Description = "いちじてきに クリティカルりつと クリティカルダメージを たかめる", SkillType = "Buff", Cooldown = 5, IsTurnFree = true, Bonus3Effect = "クールダウン-1", Bonus8Effect = "クールダウン-1" } },
            { "unmoving_stance", new Skill { Name = "せいがんのかまえ", Description = "ふどうのかまえで しばらくのあいだ こうげきのたびに こうげきりょくがあがる", SkillType = "Buff", Cooldown = 5, IsTurnFree = true, Bonus3Effect = "かくとく:きょうか/10ターン", Bonus8Effect = "かくとく:きょうか/10ターン" } },
            { "god_bless", new Skill { Name = "ゴッドブレス", Description = "いちじてきに せんとうのうりょくが アップ", SkillType = "Buff", Cooldown = 6, IsTurnFree = true, Bonus3Effect = "ターンえんちょう", Bonus8Effect = "ターンえんちょう" } },
            { "treasure_hunt", new Skill { Name = "トレジャーハント", Description = "しばらくのあいだ いい たからものが でるようになる", SkillType = "Buff", Cooldown = 8, IsTurnFree = true, Bonus3Effect = "クールダウン-1", Bonus8Effect = "クールダウン-1" } },

            // デバフ系
            { "broken_clock", new Skill { Name = "くるったとけい", Description = "てきのわざの クールダウンを おおはばに おくらせる", SkillType = "Debuff", Cooldown = 0, IsTurnFree = true, BarrierCost = 2, Bonus3Effect = "スタン", Bonus8Effect = "スタン" } },
            { "corruption", new Skill { Name = "コラプション", Description = "てきのにくたいを くちはてさせ じょうたいいじょうを かけやすくする", SkillType = "Debuff", ScalingValue = "EnemyMaxHP", Cooldown = 1, IsTurnFree = true, BarrierCost = 2, Bonus3Effect = "ターンえんちょう", Bonus8Effect = "ターンえんちょう" } },
            { "blind", new Skill { Name = "ブラインド", Description = "いちじてきに てきの めいちゅうを さげる", SkillType = "Debuff", Cooldown = 3, IsTurnFree = true, Bonus3Effect = "クールダウン-1", Bonus8Effect = "クールダウン-1" } },
            { "bind", new Skill { Name = "バインド", Description = "いちじてきに てきの かいひを さげる", SkillType = "Debuff", Cooldown = 3, IsTurnFree = true, Bonus3Effect = "ターンえんちょう", Bonus8Effect = "ターンえんちょう" } },
            { "seal_boundary", new Skill { Name = "ふういんけっかい", Description = "じょうたいへんかを ふよできない じょうたいにする", SkillType = "Debuff", Cooldown = 3, IsTurnFree = true, Bonus3Effect = "ターンえんちょう", Bonus8Effect = "ターンえんちょう" } },
            { "pollution", new Skill { Name = "ポリューション", Description = "いちじてきに じょうたいいじょうを かけやすくする", SkillType = "Debuff", Cooldown = 3, IsTurnFree = true, Bonus3Effect = "ターンえんちょう", Bonus8Effect = "ターンえんちょう" } },
            { "dispel", new Skill { Name = "ディスペル", Description = "てきの こうかを すべてうちけす", SkillType = "Debuff", Cooldown = 3, IsTurnFree = true, Bonus3Effect = "てきの シールドを かいじょ", Bonus8Effect = "てきの バリアを かいじょ" } },
            { "paralyze", new Skill { Name = "パラライズ", Description = "てきのわざ1つの クールダウンを おおはばに おくらせる", SkillType = "Debuff", Cooldown = 3, IsTurnFree = true, Bonus3Effect = "いりょくアップ", Bonus8Effect = "いりょくアップ" } },
            { "break_shield", new Skill { Name = "ブレイクシールド", Description = "いちじてきに てきの うけるダメージを ふやす", SkillType = "Debuff", Cooldown = 4, IsTurnFree = true, Bonus3Effect = "ターンえんちょう", Bonus8Effect = "ターンえんちょう" } },
            { "curse", new Skill { Name = "カース", Description = "てきに のろいをかけて こうげきりょくを ていかさせる", SkillType = "Debuff", Cooldown = 4, IsTurnFree = true, Bonus3Effect = "ターンえんちょう", Bonus8Effect = "ターンえんちょう" } },
            { "summing", new Skill { Name = "サミング", Description = "てきに めつぶしをあびせ しゅんかんてきに めいちゅうをさげる", SkillType = "Debuff", Cooldown = 4, IsTurnFree = true, Bonus3Effect = "クールダウン-1", Bonus8Effect = "クールダウン-1" } },
            { "slow", new Skill { Name = "スロウ", Description = "いちじてきに てきの クールダウンを ながくする", SkillType = "Debuff", Cooldown = 4, IsTurnFree = true, Bonus3Effect = "ターンえんちょう", Bonus8Effect = "ターンえんちょう" } },
            { "penetrate", new Skill { Name = "ペネトレート", Description = "てきの じゃくてんをみぬき しゅんかんてきに うけるダメージを ふやす", SkillType = "Debuff", Cooldown = 4, IsTurnFree = true, Bonus3Effect = "いりょくアップ", Bonus8Effect = "いりょくアップ" } },
            { "strong_smell", new Skill { Name = "きょうれつな におい", Description = "えがたい あくしゅうをはなち しゅんかんてきに てきの こうげきりょくをさげる", SkillType = "Debuff", Cooldown = 4, IsTurnFree = true, Bonus3Effect = "ターンえんちょう", Bonus8Effect = "ターンえんちょう" } },
            { "blood_moon", new Skill { Name = "ちぞめの つき", Description = "じしんと てき ともに きょうせんしか", SkillType = "Debuff", Cooldown = 5, IsTurnFree = true, Bonus3Effect = "かくとく:きょうか/5ターン", Bonus8Effect = "かくとく:きょうか/10ターン" } },
            { "seal_art", new Skill { Name = "ふういん じゅつ", Description = "きのわざ1つの クールダウンを げきてきに おくらせる", SkillType = "Debuff", Cooldown = 5, IsTurnFree = true, Bonus3Effect = "いりょくアップ", Bonus8Effect = "いりょくアップ" } },
            { "chill_freeze", new Skill { Name = "チルフリーズ", Description = "てきを こおらせて いちじてきに クールダウンを ながくする", SkillType = "Debuff", Cooldown = 5, IsTurnFree = true, Bonus3Effect = "ターンえんちょう", Bonus8Effect = "ターンえんちょう" } },

            // 召喚・追撃系
            { "forest_friend", new Skill { Name = "もりのともだち", Description = "もりの いきものたちを よびだし ともにたたかう", SkillType = "Buff", ScalingValue = "DEX", Cooldown = 3, IsTurnFree = true, Bonus3Effect = "ターンえんちょう", Bonus8Effect = "クールダウン-1" } },
            { "summon_demon", new Skill { Name = "サモンデーモン", Description = "ちを ぎせいにして あくまを しょうかんし いっしょにたたかわせる", SkillType = "Buff", ScalingValue = "Faith_MaxHP", Cooldown = 3, IsTurnFree = true, Bonus3Effect = "ターンえんちょう", Bonus8Effect = "クールダウン-1" } },
            { "doll", new Skill { Name = "ひとがた", Description = "ついげきをえる", SkillType = "Buff", ScalingValue = "INT", Cooldown = 5, IsTurnFree = true, Bonus3Effect = "ターンえんちょう", Bonus8Effect = "クールダウン-1" } },
            { "fire_mantra", new Skill { Name = "ほのの マントラ", Description = "じしんの HPに おうじた ついげきを える", SkillType = "Buff", ScalingValue = "CurrentHP", Cooldown = 5, Bonus3Effect = "いりょくアップ", Bonus8Effect = "いりょくアップ" } },
            { "rise_legion", new Skill { Name = "ライズレギオン", Description = "ついげきをえる", SkillType = "Buff", ScalingValue = "Shield", Cooldown = 5, Bonus3Effect = "ターンえんちょう", Bonus8Effect = "ターンえんちょう" } },
            { "summon_zombie", new Skill { Name = "サモンゾンビ", Description = "ゾンビをよびおこし いっしょにたたかわせる", SkillType = "Buff", ScalingValue = "Faith", Cooldown = 5, IsTurnFree = true, Bonus3Effect = "ターンえんちょう", Bonus8Effect = "クールダウン-1" } },
            { "companion", new Skill { Name = "コンパニオン", Description = "おおかみを よびだし ともにたたかう", SkillType = "Buff", ScalingValue = "DEX", Cooldown = 5, IsTurnFree = true, Bonus3Effect = "ターンえんちょう", Bonus8Effect = "クールダウン-1" } },
            { "summon_eldritch", new Skill { Name = "サモンエルドリッチ", Description = "おぞましい なにかを よびよせる", SkillType = "Buff", ScalingValue = "Shield", Cooldown = 6, Bonus3Effect = "クールダウン-1", Bonus8Effect = "クールダウン-1" } },
            { "summon_skeleton", new Skill { Name = "サモンスケルトン", Description = "がいこつぐんだんを よびおこし いっしょにたたかわせる", SkillType = "Buff", ScalingValue = "Faith", Cooldown = 7, IsTurnFree = true, Bonus3Effect = "ターンえんちょう", Bonus8Effect = "クールダウン-1" } },
            { "summon_nightmare", new Skill { Name = "サモンナイトメア", Description = "ナイトメアを しょうかんし ともにたたかう", SkillType = "Buff", ScalingValue = "INT", Cooldown = 8, IsTurnFree = true, Bonus3Effect = "ターンえんちょう", Bonus8Effect = "クールダウン-1" } },
            { "avatar", new Skill { Name = "アバター", Description = "いくさのかみを よびおろし ともにたたかう", SkillType = "Buff", ScalingValue = "STR", Cooldown = 10, IsTurnFree = true, Bonus3Effect = "ターンえんちょう", Bonus8Effect = "クールダウン-1" } },
            { "summon_dragon", new Skill { Name = "サモンドラゴン", Description = "ドラゴンを しょうかんし ともにたたかう", SkillType = "Buff", ScalingValue = "INT", Cooldown = 10, IsTurnFree = true, Bonus3Effect = "ターンえんちょう", Bonus8Effect = "クールダウン-1" } },

            // 特殊
            { "devil_strike", new Skill { Name = "あくまの いちげき", Description = "666ダメージを あたえる", Cooldown = 5, Bonus3Effect = "いりょくアップ", Bonus8Effect = "いりょくアップ" } },
            { "ascension", new Skill { Name = "しょうてん", Description = "てんに おくりかえす しんばつの いちげき", ScalingValue = "CurrentHP", Cooldown = 8, Bonus3Effect = "ターンたんしゅく", Bonus8Effect = "ターンたんしゅく" } },
            { "great_wave", new Skill { Name = "おおなみ", Description = "おおなみを まきおこし てきを のみこむ", ScalingValue = "CurrentHP", Cooldown = 8, Bonus3Effect = "いりょくアップ", Bonus8Effect = "いりょくアップ" } },
            { "death_word", new Skill { Name = "デスワード", Description = "いちげきで てきのいのちをうびさる きけんなじゅもん", Cooldown = 10, Bonus3Effect = "クールダウン-1", Bonus8Effect = "クールダウン-1" } },

            // 敵用・追加
            { "bite", new Skill { Name = "噛み付く", Description = "鋭い牙で噛み付く", Power = 15, ScalingValue = "STR", Cooldown = 2 } },
            { "heavy_blow", new Skill { Name = "叩きつける", Description = "力まかせに叩きつける", Power = 25, ScalingValue = "STR", Cooldown = 3 } },
            { "dragon_breath", new Skill { Name = "竜の息吹", Description = "すべてを焼き尽くす炎", Power = 40, ScalingValue = "INT", Cooldown = 5 } },
        };

        public static Skill GetSkill(string id)
        {
            if (Skills.TryGetValue(id, out var template))
            {
                return new Skill
                {
                    SkillId = Guid.NewGuid().ToString("N"),
                    Name = template.Name,
                    Description = template.Description,
                    Cooldown = template.Cooldown,
                    CurrentCooldown = 0,
                    Power = template.Power,
                    SkillType = template.SkillType,
                    ScalingValue = template.ScalingValue,
                    IsTurnFree = template.IsTurnFree,
                    BarrierCost = template.BarrierCost,
                    IsPreemptive = template.IsPreemptive,
                    Bonus3Effect = template.Bonus3Effect,
                    Bonus8Effect = template.Bonus8Effect,
                    AppliesToSelf = template.AppliesToSelf
                };
            }
            return new Skill { Name = "不明なスキル", Cooldown = 0 };
        }
    }
}
